services:
  private-gpt:
    # image: allfunc/privategpt:latest

    build:
      dockerfile: Dockerfile.local
      
    volumes:
      - /srv/dev-disk-by-uuid-17681c56-e3a1-4eb9-95da-2196a64acca3/configs/privateGPT/local_data/conf:/home/worker/app/local_data
      - /srv/dev-disk-by-uuid-17681c56-e3a1-4eb9-95da-2196a64acca3/configs/privateGPT/models/:/home/worker/app/models
    networks:
      - gpt-net
    ports:
      - 8001:8080
    restart: on-failure
    environment:
      PORT: 8080
      PGPT_PROFILES: docker
      PGPT_MODE: local

networks:
  gpt-net:
    name: macvlan0
    driver: macvlan
    external: true
